In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
pd.set_option('display.max_rows', None)

In [2]:
# read in the salary data and see the inconsistencies made from the damn pdf parser

In [3]:
df = pd.read_csv('../output/salaries.csv')

In [4]:
df.head()

,year,club,last_name,first_name,position,base_salary,guaranteed_comp
0,2025,Atlanta United,Miranchuk,Aleksey,ATTACKING MIDFIELD,"$3,600,000.00","$4,885,441.00"
1,2025,Atlanta United,Latte Lath,Emmanuel,CENTER FORWARD,"$3,534,546.00","$4,030,546.00"
2,2025,Atlanta United,Thiaré,Jamal,CENTER FORWARD,"$700,000.00","$730,000.00"
3,2025,Atlanta United,Togashi,Cayman,CENTER FORWARD,"$104,000.00","$104,000.00"
4,2025,Atlanta United,Mihaj,Enea,CENTER-BACK,"$1,030,000.00","$1,372,000.00"

In [5]:
df.shape # dang, 11k rows

(12491, 7)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12491 entries, 0 to 12490
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   year             12491 non-null  int64
 1   club             12378 non-null  object
 2   last_name        12381 non-null  object
 3   first_name       12313 non-null  object
 4   position         11359 non-null  object
 5   base_salary      12491 non-null  object
 6   guaranteed_comp  12491 non-null  object
dtypes: int64(1), object(6)
memory usage: 683.2+ KB

In [7]:
# alright so we are already in trouble
# things that went right:
# - data types are correct
# things that went wrong:
# - null values belonging to club, lastname, firstname, position

In [8]:
# let's analyze this to see the problem
missing_values_df = df[df.isna().any(axis=1)]

In [9]:
missing_values_df.shape

(1203, 7)

In [10]:
# split by year to handle each one
years_split_dict = {year: group for year, group in missing_values_df.groupby('year')}

In [11]:
years_split_dict.keys()

dict_keys([2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024])

In [12]:
missing_values_df.year.value_counts()

year
2024    910
2023     30
2011     30
2015     27
2016     26
2014     25
2018     23
2017     21
2012     20
2013     19
2022     17
2021     11
2010     10
2020      7
2019      7
2009      7
2008      7
2007      6
Name: count, dtype: int64

In [13]:
# this function represents the cleanse of each group in missing_values_df
def cleanse_null_values(data):
    # main_df should be the main dataframe
    _missing_values_df = df[df.isna().any(axis=1)]
    print(f"there are {_missing_values_df.shape[0]} rows containing null values")
    _years_split_dict = {year: group for year, group in missing_values_df.groupby('year')}
    print(f"there are null values found within each of these years: {_years_split_dict.keys()}")
    # --- YEAR 2007-2009 ---
    _current_years_analyzing = [2007, 2008, 2009]
    for year in _current_years_analyzing:
        current_year_df_missing = _years_split_dict[year].isna().any(axis=1)
        data.drop(index=current_year_df_missing.index, inplace=True)
    
  
    # --- YEAR 2010 ---
    # -- we need to drop all rows where first_name and salary is na()
    current_year_analyzing = 2010
    current_year_df = _years_split_dict[current_year_analyzing]
    mask = (current_year_df["first_name"].isna()) & (current_year_df['base_salary'].astype(str).str.strip() == str(current_year_analyzing))
    to_drop = current_year_df.loc[mask]
    data.drop(index=to_drop.index, inplace=True)
    
    
    # --- YEAR 2011 ---
    current_year_analyzing = 2011
    current_year_df = _years_split_dict[current_year_analyzing]
    
    # --- YEAR 2012 ---
    current_year_analyzing = 2012
    current_year_df = _years_split_dict[current_year_analyzing]
    
    # --- YEAR 2013 ---
    current_year_analyzing = 2013
    current_year_df = _years_split_dict[current_year_analyzing]
    
    # --- YEAR 2014 ---
    current_year_analyzing = 2014
    current_year_df = _years_split_dict[current_year_analyzing]
    
    # --- YEAR 2015 ---
    current_year_analyzing = 2015
    current_year_df = _years_split_dict[current_year_analyzing]
    
    # --- YEAR 2016 ---
    current_year_analyzing = 2016
    current_year_df = _years_split_dict[current_year_analyzing]
    
    # --- YEAR 2017 ---
    current_year_analyzing = 2017
    current_year_df = _years_split_dict[current_year_analyzing]
    
    # --- YEAR 2018 ---
    current_year_analyzing = 2018
    current_year_df = _years_split_dict[current_year_analyzing]

    # --- YEAR 2019 ---
    # current_year_analyzing = 2019
    # current_year_df = _years_split_dict[current_year_analyzing]
    
    # --- YEAR 2020 ---
    current_year_analyzing = 2020
    current_year_df = _years_split_dict[current_year_analyzing]
    
    # --- YEAR 2021 ---
    current_year_analyzing = 2021
    current_year_df = _years_split_dict[current_year_analyzing]
    
    # --- YEAR 2022 ---
    current_year_analyzing = 2022
    current_year_df = _years_split_dict[current_year_analyzing]
    
    # --- YEAR 2023 ---
    current_year_analyzing = 2023
    current_year_df = _years_split_dict[current_year_analyzing]
    
    # --- YEAR 2024 ---
    current_year_analyzing = 2024
    current_year_df = _years_split_dict[current_year_analyzing]

    data['club'] = data['club'].fillna('N/A')
    
    return data

In [14]:
# testing the function as we go
print(df.shape)
new_df = cleanse_null_values(data=df.copy())
print(new_df.shape)
print(df.shape)

(12491, 7)
there are 1203 rows containing null values
there are null values found within each of these years: dict_keys([2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024])
(12464, 7)
(12491, 7)

In [15]:
missing_values_new_df = new_df[new_df.isna().any(axis=1)]

In [16]:
missing_values_new_df.year.value_counts()

year
2024    910
2023     30
2011     30
2015     27
2016     26
2014     25
2018     23
2017     21
2012     20
2013     19
2022     17
2021     11
2020      7
2019      7
Name: count, dtype: int64

---

In [17]:
years_split_dict[2011] # okay at first glance, these positions in 2007 are empty and their base salary and guranteed comp is the same year as well so I believr we can safely cut this after verification

,year,club,last_name,first_name,position,base_salary,guaranteed_comp
10401,2011,Houston Dynamo,Boswell,"Bobby D $ 210,000.00",NaN,$,"210,000.00"
10402,2011,NaN,NaN,NaN,NaN,2011,2011
10403,2011,Toronto FC,Bouchiba,"Elbekay M $ 92,004.00",NaN,$,"92,004.00"
10455,2011,Chivas USA,Courtois,"Laurent M $ 60,000.00",NaN,$,"206,000.00"
10456,2011,NaN,NaN,NaN,NaN,2011,2011
10457,2011,LA Galaxy,Cristman,"Adam F $ 42,000.00",NaN,$,"42,000.00"
10509,2011,Chivas USA,Flores,"Jorge F $ 60,000.00",NaN,$,"61,666.67"
10510,2011,NaN,NaN,NaN,NaN,2011,2011
10511,2011,Colorado Rapids,Folan,"Caleb F $ 200,000.00",NaN,$,"203,375.00"
10563,2011,Toronto FC,Henry,"Doneil D $ 42,000.00",NaN,$,"43,000.00"
10564,2011,NaN,NaN,NaN,NaN,2011,2011
10565,2011,FC Dallas,Hernandez,"Daniel M-D $ 160,000.00",NaN,$,"172,500.00"
10589,2011,Sporting Kansas City,Jeferson,NaN,F,"429,996.00$","484,996.00$"
10602,2011,Colorado Rapids,Kandji,"Macoumba F 120,000.00$",NaN,$,"147,988.37"
10617,2011,Vancouver Whitecaps,Knight,"W es M/D $ 50,000.00",NaN,$,"50,000.00"
10618,2011,NaN,NaN,NaN,NaN,2011,2011
10619,2011,Toronto FC,Kocic,"Milos GK $ 42,000.00",NaN,$,"42,000.00"
10671,2011,Real Salt Lake,McKenzie,"Rauwshan D $ 42,000.00",NaN,$,"42,000.00"
10672,2011,NaN,NaN,NaN,NaN,2011,2011
10673,2011,San Jose Earthquakes,McLoughlin,"Ellis F $ 32,600.00",NaN,$,"32,600.00"
10725,2011,Chicago Fire,Paladini,"Daniel M $ 75,000.00",NaN,$,"79,478.25"
10726,2011,NaN,NaN,NaN,NaN,2011,2011
10727,2011,Colorado Rapids,Palguta,"Scott D $ 60,638.00",NaN,$,"60,638.00"
10779,2011,Vancouver Whitecaps,Salinas,"Shea M $ 44,000.00",NaN,$,"44,000.00"
10780,2011,NaN,NaN,NaN,NaN,2011,2011
10781,2011,FC Dallas,Sanchez,"Richard GK $ 32,600.00",NaN,$,"33,600.00"
10833,2011,New England Revolution,Tierney,"Chris D-M $ 65,000.00",NaN,$,"66,666.67"
10834,2011,NaN,NaN,NaN,NaN,2011,2011
10835,2011,Real Salt Lake,Toia,"Donny F $ 45,000.00",NaN,$,"60,000.00"
10882,2011,Sporting Kansas City,Zusi,"Graham F-M $ 42,000.00",NaN,$,"42,000.00"

In [18]:
t = years_split_dict[2011]

In [22]:
salary_missing = t.loc[(t.base_salary.str.strip() == '$')]

In [23]:
salary_missing

,year,club,last_name,first_name,position,base_salary,guaranteed_comp
10401,2011,Houston Dynamo,Boswell,"Bobby D $ 210,000.00",NaN,$,"210,000.00"
10403,2011,Toronto FC,Bouchiba,"Elbekay M $ 92,004.00",NaN,$,"92,004.00"
10455,2011,Chivas USA,Courtois,"Laurent M $ 60,000.00",NaN,$,"206,000.00"
10457,2011,LA Galaxy,Cristman,"Adam F $ 42,000.00",NaN,$,"42,000.00"
10509,2011,Chivas USA,Flores,"Jorge F $ 60,000.00",NaN,$,"61,666.67"
10511,2011,Colorado Rapids,Folan,"Caleb F $ 200,000.00",NaN,$,"203,375.00"
10563,2011,Toronto FC,Henry,"Doneil D $ 42,000.00",NaN,$,"43,000.00"
10565,2011,FC Dallas,Hernandez,"Daniel M-D $ 160,000.00",NaN,$,"172,500.00"
10602,2011,Colorado Rapids,Kandji,"Macoumba F 120,000.00$",NaN,$,"147,988.37"
10617,2011,Vancouver Whitecaps,Knight,"W es M/D $ 50,000.00",NaN,$,"50,000.00"
10619,2011,Toronto FC,Kocic,"Milos GK $ 42,000.00",NaN,$,"42,000.00"
10671,2011,Real Salt Lake,McKenzie,"Rauwshan D $ 42,000.00",NaN,$,"42,000.00"
10673,2011,San Jose Earthquakes,McLoughlin,"Ellis F $ 32,600.00",NaN,$,"32,600.00"
10725,2011,Chicago Fire,Paladini,"Daniel M $ 75,000.00",NaN,$,"79,478.25"
10727,2011,Colorado Rapids,Palguta,"Scott D $ 60,638.00",NaN,$,"60,638.00"
10779,2011,Vancouver Whitecaps,Salinas,"Shea M $ 44,000.00",NaN,$,"44,000.00"
10781,2011,FC Dallas,Sanchez,"Richard GK $ 32,600.00",NaN,$,"33,600.00"
10833,2011,New England Revolution,Tierney,"Chris D-M $ 65,000.00",NaN,$,"66,666.67"
10835,2011,Real Salt Lake,Toia,"Donny F $ 45,000.00",NaN,$,"60,000.00"
10882,2011,Sporting Kansas City,Zusi,"Graham F-M $ 42,000.00",NaN,$,"42,000.00"

In [29]:
new_cols = salary_missing['first_name'].str.rsplit(n=3, expand=True)
salary_missing.first_name = new_cols[0]
salary_missing.

SyntaxError: invalid syntax (1448015343.py, line 3)